/**
 * Exports the derived governed clinical snapshot as a committed, checksummed
 * fixture so a clean checkout can run the clinical suites without the external
 * source package.
 *
 * See docs/canonical-cutover/13-source-artifact-and-reproducibility.md.
 *
 * The snapshot is DERIVED, never authored. Regenerate it with:
 *
 *     npm run rules:export:snapshot
 *
 * The source-verification suite rebuilds from the external package and asserts
 * the committed fixture is byte-identical, so the fixture can never silently
 * drift from the source it claims to represent.
 */

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { calculateRuleSnapshotChecksum, deterministicJson } from "../../lib/clinical-rules/checksum";
import { buildSuccessorSnapshotFromV21Package } from "../../lib/clinical-rules/successor-v3-1";
import { buildSnapshotFromV21Package } from "../../lib/clinical-rules/source-package";

const OUTPUT_DIRECTORY = path.join(process.cwd(), "lib/clinical-rules/governed-snapshots");

async function main() {
  const base = await buildSnapshotFromV21Package();
  const successor = await buildSuccessorSnapshotFromV21Package();

  await mkdir(OUTPUT_DIRECTORY, { recursive: true });

  const artefacts = [
    { name: "cg-ncsp-3.0.0", snapshot: base.snapshot },
    { name: "cg-ncsp-3.1.0", snapshot: successor.snapshot },
  ];

  const manifest: Record<string, { checksum: string; rules: number; bytes: number }> = {};

  for (const artefact of artefacts) {
    const json = deterministicJson(artefact.snapshot);
    const checksum = calculateRuleSnapshotChecksum(artefact.snapshot);
    const file = path.join(OUTPUT_DIRECTORY, `${artefact.name}.json`);
    await writeFile(file, `${json}\n`, "utf8");
    manifest[artefact.name] = {
      checksum,
      rules: artefact.snapshot.rules.length,
      bytes: Buffer.byteLength(json, "utf8"),
    };
    console.log(
      `${artefact.name}: ${artefact.snapshot.rules.length} rules, ` +
        `${(Buffer.byteLength(json, "utf8") / 1024).toFixed(0)} KiB, checksum ${checksum}`
    );
  }

  await writeFile(
    path.join(OUTPUT_DIRECTORY, "manifest.json"),
    `${JSON.stringify(
      {
        note:
          "Derived governed clinical snapshots. Generated by scripts/rule-studio/export-governed-snapshot.ts " +
          "from the external v2.1 source package. Never hand-edit. " +
          "See docs/canonical-cutover/13-source-artifact-and-reproducibility.md.",
        sourcePackageVersion: successor.snapshot.sourcePackage.version,
        sourceJsonSha256: successor.snapshot.sourcePackage.sourceJsonSha256,
        artefacts: manifest,
      },
      null,
      2
    )}\n`,
    "utf8"
  );

  console.log(`\nWrote ${OUTPUT_DIRECTORY}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
